import StyledComponentsRegistry from "@/src/app/registry";
import { ReactNode } from "react";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  header,
  grid,
  chooseName,
  access,
}: {
  children: ReactNode;
  header: ReactNode;
  grid: ReactNode;
  chooseName: ReactNode;
  access: ReactNode;
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body>
          {/* Рендер параллельных маршрутов */}
          {header}
          <div id={"access-section"}>
            {access}
            {grid}
            {chooseName}
          </div>
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
